services:
  builder_centos8:
    build:
      dockerfile: builder_centos8_glibc_2.28/Dockerfile
    volumes:
      - .:/app
      - maven-cache:/root/.m2
      - ./builder_centos8_glibc_2.28/output:/build-output
    working_dir: /app
    environment:
      - MAVEN_PROFILE=${MAVEN_PROFILE:-}
    command: >
      sh -c "
        echo 'Starting build process...' &&
        ./mvnw clean package -P${MAVEN_PROFILE} &&
        echo 'Copying artifacts to output...' &&
        mkdir -p /build-output &&
        cp target/secOpsDispatcher /build-output || echo 'No excutable found' &&
        ls -la /build-output/ &&
        echo 'Build completed successfully!'
      "

  builder_centos7:
    build:
      dockerfile: builder_centos7_glibc_2.17/Dockerfile
    volumes:
      - .:/app
      - maven-cache:/root/.m2
      - ./builder_centos7_glibc_2.17/output:/build-output
    working_dir: /app
    environment:
      - MAVEN_PROFILE=${MAVEN_PROFILE:-}
    command: >
      sh -c "
        echo 'Starting build process...' &&
        ./mvnw clean package -P${MAVEN_PROFILE} &&
        echo 'Copying artifacts to output...' &&
        mkdir -p /build-output &&
        cp target/secOpsDispatcher /build-output/secOpsDispatcher_glibc_2.17 || echo 'No excutable found' &&
        ls -la /build-output/ &&
        echo 'Build completed successfully!'
      "
volumes:
  maven-cache:
    driver: local