services:
  builder_centos8:
    build:
      dockerfile: builder_centos8/Dockerfile
    container_name: secopsdispatcher_builder
    volumes:
      - .:/app
      - maven-cache:/root/.m2
      - ./builder_centos8/output:/build-output
    working_dir: /app
    environment:
      - MAVEN_PROFILE=${MAVEN_PROFILE:-}
    command: >
      sh -c "
        echo 'Starting build process...' &&
        ./mvnw clean package -P${MAVEN_PROFILE} &&
        echo 'Copying artifacts to output...' &&
        mkdir -p /build-output &&
        cp target/secOpsDispatcher /build-output/secOpsDispatcher_glibc_2.28 || echo 'No excutable found' &&
        ls -la /build-output/ &&
        echo 'Build completed successfully!'
      "

volumes:
  maven-cache:
    driver: local